/// <reference path="../config/config.ts"/>
/// <reference path="../objects/label.ts"/>
/// <reference path="../objects/gameObject.ts"/>
/// <reference path="../objects/player.ts"/>
/// <reference path="../objects/zombie.ts"/>
/// <reference path="../objects/scene.ts"/>
/// <reference path="../core/keyBoardInput.ts"/>
/// <reference path="../core/collision.ts"/>
/// <reference path="../scenes/start.ts"/>
/// <reference path="../scenes/play.ts"/>
///// <reference path="../scenes/end.ts"/>
//# sourceMappingURL=reference.js.map